#CUDA_VISIBLE_DEVICES=0 python tc_img2img_control_inference.py \
#--model_type="potato" \
#--model_id="/home/Antares.Guo/train_model/0818_tc_ftcontrolonly_loadunet_sd15potato_sks+mr+potato+head_lr1e-5" \
#--token_path="" \
#--attn_path="" \
#--replace_token="sks+mr+potato+head" \
#--seed=1024 \
#--pose_model="/home/Antares.Guo/code/diffusers/models/ControlNet/annotator/ckpts" \
#--control_model="/home/Antares.Guo/train_model/0818_tc_ftcontrolonly_loadunet_sd15potato_sks+mr+potato+head_lr1e-5" \
#--save_path="/home/Antares.Guo/tmp_img/potato_control/strength09_noprompt" \
#--control_img_dir="/home/Antares.Guo/data/control_template" \
#--TE_pose_file="/home/Antares.Guo/data/potato/2.json" \
#--strength=0.9 --num_inference_steps 40 \
#--b_align --prompt_type="no"
#
#CUDA_VISIBLE_DEVICES=0 python tc_img2img_control_inference.py \
#--model_type="potato" \
#--model_id="/home/Antares.Guo/code/diffusers/models/mr-potato-head" \
#--token_path="" \
#--attn_path="" \
#--replace_token="sks+mr+potato+head" \
#--seed=1024 \
#--pose_model="/home/Antares.Guo/code/diffusers/models/ControlNet/annotator/ckpts" \
#--control_model="/home/Antares.Guo/code/diffusers/models/sd-controlnet-openpose" \
#--save_path="/home/Antares.Guo/tmp_img/potato/strength09_noprompt" \
#--control_img_dir="/home/Antares.Guo/data/control_template" \
#--TE_pose_file="/home/Antares.Guo/data/potato/2.json" \
#--strength=0.9 --num_inference_steps 40 \
#--b_align --prompt_type="no"

CUDA_VISIBLE_DEVICES=0 python tc_img2img_control_inference.py \
--model_type="yan" \
--model_id="/data1/tc_guo/train_model/1114_tc_ftunetonly_sd15_sks+blue+bird_plushie_lr1e-5" \
--token_path="" \
--attn_path="" \
--replace_token="sks+blue+bird+plushie" \
--seed=1024 \
--pose_model="/home/Antares.Guo/code/diffusers/models/ControlNet/annotator/ckpts" \
--control_model="/home/Antares.Guo/train_model/0818_tc_ftcontrolonly_loadunet_sd15potato_sks+mr+potato+head_lr1e-5" \
--save_path="/home/Antares.Guo/tmp_img/1110yan" \
--control_img_dir="/home/Antares.Guo/data/control_template" \
--TE_pose_file="/data1/tc_guo/data/yanbird/bird_template.json" \
--strength=0.9 --num_inference_steps 40 \
--b_align --prompt_type="user"