positive_promot_str = " best quality"

negative_prompt_str = "worst quality, poorly drawn, extra limb, missing limb, floating limbs, mutated hands, extra fingers, disconnected limbs, mutation, mutated, ugly, disgusting, low quality,lowres, bad anatomy, bad hands, cropped, worst quality,"

unique_identifier = "unique_identifier"

# type
# key:[img_name, pose_name,auto_prompt,user_prompt]
# note: the pose img's shape is resized, is not equal to the shape of the img
action_dict_list = {
    "badminton": ["badminton.jpg", "badminton.jpg", "a unique_identifier playing badminton,",
                  "a unique_identifier playing badminton in front of the badminton net,"],
    "badminton2": ["badminton2.jpeg", "badminton.jpg", "a unique_identifier playing badminton,",
                   "a unique_identifier playing badminton in front of the badminton net,"],
    "basketball2": ["basketball2.jpeg", "basketball2.jpeg",
                    "a unique_identifier is a basketball player who is dribbling the ball while another player is guarding him,",
                    "A unique_identifier plays basketball,movie style,basketball on unique_identifier's hand,"],
    "basketball": ["basketball.png", "basketball.png", "a unique_identifier is play basketball,",
                   "A unique_identifier plays basketball,movie style,basketball on unique_identifier's hand,"],
    "bike_front": ["bike_front.jpeg", "bike_front.jpeg", "a unique_identifier riding a bike,",
                   "A unique_identifier is riding a bike on the street,"],
    "bike_side": ["bike_side.jpeg", "bike_side.jpeg",
                  "a unique_identifier riding a bike on the road near the ocean,",
                  "a unique_identifier riding a bike on the road near the ocean,"],
    "child_tennis2": ["child_tennis2.jpeg", "child_tennis2.jpeg", "a unique_identifier is playing tennis on a court,",
                      "A unique_identifier is holding a tennis racket on his left hand and playing tennis on Wimbledon tennis tournament, feel the Olympic spirit, A 18mm Wide-angle perspective photo , hyper realistic, summer vibe, sun shine, sunny and bright, 32k, super details, photorealistic,"],
    "fencing2": ["fencing2.jpg", "fencing2.jpg", "a unique_identifier in fencing gear is holding a sword,",
                 "A unique_identifier is fencing, ready to embrace the challenge,gracefully swings the sword, performing fluid and precise fencing moves with speed and accuracy, showcasing the perfect fusion of technology and sports,"],
    "football2": ["football2.jpg", "football2.jpg", "a unique_identifier in red soccer uniform kicking a soccer ball,",
                  "A unique_identifier iskicking a soccer ball, the football leaves its foot, realistic,sports photography, side view to unique_identifier,"],
    "football3": ["football3.jpeg", "football3.jpeg", "a unique_identifier kicking a soccer ball,",
                  "A unique_identifier iskicking a soccer ball, the football leaves its foot, realistic,sports photography, side view to unique_identifier,"],
    "football4": ["football4.jpeg", "football4.jpeg", "a unique_identifier kicking a soccer ball,",
                  "A unique_identifier iskicking a soccer ball, the football leaves its foot, realistic,sports photography, side view to unique_identifier,"],
    "football": ["football.jpeg", "football.jpeg", "a unique_identifier kicking a soccer ball,",
                 "A unique_identifier iskicking a soccer ball, the football leaves its foot, realistic,sports photography, side view to unique_identifier,"],
    "keeper2": ["keeper2.jpg", "keeper2.jpg",
                "a unique_identifier is a soccer goalkeeper catching the ball in the air,",
                "A unique_identifier is a goalkeeper, try to touch the football, saving a football, realistic,sports photography , front view to the football gate,"],
    "keeper3": ["keeper3.jpeg", "keeper3.jpeg", "a unique_identifier catching a ball,",
                "A unique_identifier is a goalkeeper, try to touch the football, saving a football, realistic,sports photography , front view to the football gate,"],
    "keeper4": ["keeper4.jpeg", "keeper4.jpeg", "a unique_identifier is a goalkeeper who is diving to catch the ball,",
                "A unique_identifier is a goalkeeper, try to touch the football, saving a football, realistic,sports photography , front view to the football gate,"],
    "keeper5": ["keeper5.jpeg", "keeper5.jpeg", "a unique_identifier is a soccer player who is diving to catch a ball,",
                "A unique_identifier is a goalkeeper, try to touch the football, saving a football, realistic,sports photography , front view to the football gate,"],
    "keeper": ["keeper.jpeg", "keeper.jpeg", "a unique_identifier is a soccer player who is jumping to catch the ball,",
               "A unique_identifier is a goalkeeper, try to touch the football, saving a football, realistic,sports photography , front view to the football gate,"],
    "left_hand_up": ["left_hand_up.jpeg", "left_hand_up.jpeg",
                     "a unique_identifier in a white t - shirt and jeans is making the peace sign,",
                     "A unique_identifier raises left hand up,"],
    "lie": ["lie.jpeg", "lie.jpeg", "a unique_identifier laying on a couch with his feet up,",
            "A unique_identifier lying on the sofa,"],
    "pose10": ["pose10.jpeg", "pose10.jpeg", "a unique_identifier is jumping in the air,", ""],
    "pose11": ["pose11.jpeg", "pose11.jpeg", "a unique_identifier is a ballerina,", ""],
    "pose12": ["pose12.jpg", "pose12.jpg", "a unique_identifier is dancing,", ""],
    "pose13": ["pose13.jpeg", "pose13.jpeg", "a unique_identifier is dancing,", ""],
    "pose14": ["pose14.jpeg", "pose14.jpeg", "a unique_identifier is dancing in the grass,", ""],
    "pose15": ["pose15.jpeg", "pose15.jpeg", "a unique_identifier doing a ballet pose,", ""],
    "pose17": ["pose17.jpeg", "pose17.jpeg", "a unique_identifier posing for a photo,", ""],
    "pose18": ["pose18.jpeg", "pose18.jpeg", "a unique_identifier is dancing in the garden,", ""],
    "pose19": ["pose19.jpeg", "pose19.jpeg", "a unique_identifier is jumping in the air,", ""],
    "pose1": ["pose1.jpeg", "pose1.jpeg", "a unique_identifier dancing in silhouette,", ""],
    "pose20": ["pose20.jpg", "pose20.jpg", "a unique_identifier doing tai chi in front of a pond,", ""],
    "pose21": ["pose21.jpeg", "pose21.jpeg", "a unique_identifier posing for the camera,", ""],
    "pose22": ["pose22.jpeg", "pose22.jpeg", "a unique_identifier doing tai chi on a bridge,", ""],
    "pose23": ["pose23.jpeg", "pose23.jpeg", "a unique_identifier jumps in the air,", ""],
    "pose24": ["pose24.jpg", "pose24.jpg", "a unique_identifier is doing a workout,", ""],
    "pose2": ["pose2.jpeg", "pose2.jpeg", "a unique_identifier doing a dance,", ""],
    "pose3": ["pose3.jpeg", "pose3.jpeg", "a unique_identifier doing a dance,", ""],
    "pose4": ["pose4.jpeg", "pose4.jpeg", "a unique_identifier dancing on the street,", ""],
    "pose5": ["pose5.jpeg", "pose5.jpeg", "a unique_identifier is jumping in the air,", ""],
    "pose7": ["pose7.jpeg", "pose7.jpeg", "a unique_identifier is a dancer who is jumping,", ""],
    "right_hand_up": ["right_hand_up.jpeg", "right_hand_up.jpeg", "a unique_identifier is standing,", ""],
    "runner2": ["runner2.jpeg", "runner2.jpeg", "a unique_identifier running on the beach,", ""],
    "runner": ["runner.jpeg", "runner.jpeg", "a unique_identifier running on a road in the middle of the day,", ""],
    "shoot": ["shoot.jpeg", "shoot2.jpeg", "a unique_identifier kicking a soccer ball,",
              "A unique_identifier is shootting the goal, the football leaves its foot, soaring towards the goal, realistic,sports photography, side view to unique_identifier,"],
    "sit": ["sit.jpeg", "sit.jpeg", "a unique_identifier using smartphone at cafe,",
            "A unique_identifier sit in chair, drinking coffee. side view to unique_identifier, in the coffee shop, at dusk, aestheticism,"],
    "skiing1": ["skiing1.jpg", "skiing1.jpg", "a unique_identifier skiing down a snowy mountain,",
                "A unique_identifier Wearing a very big sled, skiing from high with a burst of speed, leaving a trail of flying snowflakes in its wake,"],
    "skiing2": ["skiing2.jpeg", "skiing2.jpeg", "a unique_identifier is holding her skis up,",
                "A unique_identifier Wearing a very big sled, skiing from high with a burst of speed, leaving a trail of flying snowflakes in its wake,"],
    "skiing3": ["skiing3.jpg", "skiing3.jpg", "a unique_identifier skiing down a slope,",
                "A unique_identifier Wearing a very big sled, skiing from high with a burst of speed, leaving a trail of flying snowflakes in its wake,"],
    "slamdunk3": ["slamdunk3.jpeg", "slamdunk3.jpeg", " a unique_identifier in a purple jersey,",
                  "A unique_identifier plays basketball, shoot the basket, jump highly,  slamdunk, basketball hoop, movie style,view to unique_identifier,"],
    "slamdunk4": ["slamdunk4.jpeg", "slamdunk4.jpeg",
                  "a unique_identifier is a basketball player in the air with his hands up,",
                  "A unique_identifier plays basketball, shoot the basket, jump highly,  slamdunk, basketball hoop, movie style,view to unique_identifier,"],
    "slamdunk": ["slamdunk.jpg", "slamdunk.jpg", "a unique_identifier is a basketball player who is dunking the ball,",
                 "A unique_identifier plays basketball, shoot the basket, jump highly,  slamdunk, basketball hoop, movie style,view to unique_identifier,"],
    "softball": ["softball.jpeg", "softball.jpeg", "a unique_identifier throwing a ball,", ""],
    "stand2": ["stand2.jpeg", "stand2.jpeg", "a unique_identifier holding a bunch of red balloonsm",
               "A unique_identifier is wearing in wizard hat , on Hallowmas style,  with pumpkin monster, ghost style, dark style,"],
    "stand": ["stand.jpeg", "stand.jpeg", "a unique_identifier is standing,",
              "A unique_identifier is wearing in Santa hat ,Full-body portrait,front view to unique_identifier,"],
    "surfing": ["surfing.jpeg", "surfing.jpeg", "a unique_identifier riding a surfboard,",
                "A unique_identifier gracefully stands on the surfboard while surfing, soaring over the crest of the wave, a massive wave approaches,Splashes of water, blue sea"],
    "tennis": ["tennis.jpeg", "tennis.jpeg", "a unique_identifier is playing tennis,",
               "A unique_identifier play tennis, with a tennis racket in his hand,sunshine, view to the unique_identifier,"],
    "volleyball1": ["volleyball1.jpeg", "volleyball1.jpeg", "a unique_identifier is jumping to catch a volleyball,",
                    "A unique_identifier is jumping on the volleyball court, ready to spike the ball, As the volleyball rises, the unique_identifier swiftly adjusts its position and then forcefully swings its arms, launching a powerful spike. "],
    "welcome": ["welcome.jpeg", "welcome.jpeg", "a unique_identifier is holding something,",
                "A unique_identifier is wearing chef hat in the dinner room, Full-length portrait,front view to unique_identifier, wide view,"],
    "yoga2": ["yoga2.jpeg", "yoga2.jpeg", "a unique_identifier in a yoga pose with her arms outstretched,", ""],
    "yoga": ["yoga.jpeg", "yoga.jpeg", "a unique_identifier in a yoga pose with arms outstretched,", ""],
}
